- data/resources/style.css
- data/resources/ui/image-row.ui
Instead, apply font size for `PropertyRow`s selectively in `ImageRow`.
> style: Don't touch font size of `PropertyRow`

- src/model/container_list.rs
- src/model/image_list.rs
- src/window.rs
We tunnel events to the object where the event is needed. We can also
get rid of the periodic checking of the podman service, since the event
stream will be interrupted if we lost contact with podman.
> arch: Use a single event listener for podman

- src/model/image.rs
- src/view/image_row.rs
- src/view/images_panel.rs
- src/window.rs
The improvements include
1. overall better feedback in the form of toasts
2. prune action is disabled during prune process
> images-panel: Improve pruning and deletion process

- po/LINGUAS
- po/nl.po
This adds a translation file for Dutch (usable for The Netherlands and Flemish Belgium).
Closes #81.
> Add Dutch translation

- src/view/images_panel.rs
In this way, we don't need to recreate them whenever the image list is
set.
In addition, provide an API to update them from outside.
> images-panel: Save filters/sorter as struct members

- po/es.po
- po/fr.po
- po/it.po
This reverts commit 943575dc3006f274705d55296c6da46b1c267d5a, reversing
changes made to 81fd5accf7e7e205ece875bf204f49801996c5ef.
> Revert "Merge pull request #120 from weblate/weblate-pods-pods"

- Cargo.lock
- Cargo.toml
- data/resources/resources.gresource.xml
- data/resources/style.css
- data/resources/ui/container-logs-panel.ui
- data/resources/ui/container-page.ui
- data/resources/ui/text-search-entry.ui
- src/view/container/container_logs_panel.rs
- src/view/container/container_page.rs
- src/view/mod.rs
- src/view/text_search_entry.rs
- src/window.rs
> Implement search function for container logs

- src/view/container/container_logs_panel.rs
The `SourceView` still had a light color scheme when dark mode was
applied. This commit provides a fix by setting the scheme to
`Adwaita-dark` in this case.
> container-logs-panel: Adapt to dark mode

- Cargo.lock
- Cargo.toml
- data/resources/resources.gresource.xml
- data/resources/ui/container-creation-dialog.ui
- data/resources/ui/env-var-row.ui
- data/resources/ui/image-details-page.ui
- data/resources/ui/image-row.ui
- data/resources/ui/port-mapping-row.ui
- data/resources/ui/volume-row.ui
- src/model/env_var.rs
- src/model/mod.rs
- src/model/port_mapping.rs
- src/model/volume.rs
- src/view/container/container_creation_dialog.rs
- src/view/container/env_var_row.rs
- src/view/container/mod.rs
- src/view/container/port_mapping_row.rs
- src/view/container/volume_row.rs
- src/view/image/image_details_page.rs
- src/view/image/image_row.rs
- src/view/image/images_panel.rs
- src/view/image/mod.rs
- src/view/mod.rs
> Implement container creation dialog

- data/icons/com.github.marhkb.Pods-symbolic.svg
- data/icons/com.github.marhkb.Pods.Devel.svg
- data/icons/com.github.marhkb.Pods.svg
- src/application.rs
> Add application icons

- src/view/container/container_creation_page.rs
This fxes a crash when a container is to be created from an image.
> container-creation-page: Use the available `Client`

- data/resources/ui/container-creation-page.ui
- data/resources/ui/image-pull-page.ui
- data/resources/ui/image-selection-page.ui
- src/main.rs
- src/model/client.rs
- src/model/container.rs
- src/model/container_list.rs
- src/model/image.rs
- src/model/image_list.rs
- src/search_provider.rs
- src/view/container/container_creation_page.rs
- src/view/image/image_pulling_page.rs
- src/view/image/image_search_widget.rs
- src/view/image/image_selection_page.rs
- src/view/info_dialog.rs
- src/window.rs
This should make it easier to implement a session manager.
> kaizen: Move lazy static `Podman` into `Client`

- src/model/simple_container_list.rs
- src/view/image/image_menu_button.rs
> Show confirmation dialog when deleting images with containers

- src/model/container.rs
- src/model/container_list.rs
The endpoint `containers/{name}/stats` is marked as deprecated. Instead,
we use `containers/stats` now.
> refactor(container-stats): Use newer endpoint

- Cargo.lock
- Cargo.toml
- src/api.rs
- src/main.rs
- src/model/client.rs
- src/model/connection_manager.rs
- src/model/container.rs
- src/model/container_list.rs
- src/model/image.rs
- src/model/image_config.rs
- src/model/image_details.rs
- src/model/image_list.rs
- src/model/image_search_response.rs
- src/model/pod.rs
- src/model/pod_list.rs
- src/podman.rs
- src/view/container/container_creation_page.rs
- src/view/container/container_log_page.rs
- src/view/container/container_resources_quick_reference_group.rs
- src/view/container/container_row.rs
- src/view/image/image_pull_page.rs
- src/view/image/image_pulling_page.rs
- src/view/image/image_search_widget.rs
- src/view/image/images_prune_page.rs
- src/view/info_dialog.rs
- src/view/pod/pod_creation_page.rs
- src/view/top_page.rs
In the last version of `podman-api-rs` there were a number of API breaks
that are fixed in this bulk commit.
> chore(cargo): Update dependencies

- src/model/container_list.rs
Sometimes a `ContainerStats200Response` fails to deserialize. So in such
cases, we continue listening to the stats stream.
> fix(container-stats): Always continue

- src/model/container_list.rs
Sometimes, a `ContainerStats200Response` is malformed. To prevent
crashing, we test whether the json is valid.
> fix(container-stats): Check if json is valid

- data/resources/resources.gresource.xml
- data/resources/ui/cmd-arg/row.ui
- data/resources/ui/container/creation-page.ui
- src/model/cmd_arg.rs
- src/model/mod.rs
- src/view/cmd_arg/mod.rs
- src/view/cmd_arg/row.rs
- src/view/container/creation_page.rs
- src/view/mod.rs
Initial attempt at adding a way to define command arguments when creating a container.
This work is mainly based on implementation of env-vars as I'm still trying to wrap my head around the code base so it might not be the best solution.
Closes: #328
> feat: command arguments when creating a container

- src/application.rs
> feat(about-dialog): Add vv9k as developer

- data/resources/ui/device/row.ui
It seems that something has gone wrong in #361.
> style(device-row): Make it pretty

- data/resources/ui/image/row.ui
- src/view/image/row.rs
It has everything we need for the image row.
> refactor(image-row): Use `GtkListBoxRow` as parent

- .github/workflows/ci.yml
- src/model/connection_manager.rs
- src/view/connection/row.rs
- src/view/container/health_check_page.rs
- src/view/container/properties_group.rs
- src/view/container/resources_quick_reference_group.rs
- src/view/container/row.rs
- src/view/image/details_page.rs
- src/view/image/row.rs
- src/view/images/panel.rs
- src/view/images/prune_page.rs
- src/view/pods/panel.rs
- src/view/search_panel.rs
- src/window.rs
It causes problems across different rustc versions.
> chore(ci): Fix clippy

- data/resources/style-dark.css
- data/resources/style.css
- data/resources/ui/container/row.ui
This reverts commit 741b96e6a40f5152a893f34d3af98b569ec5a6d4. The old
badge style looked better.
> Revert "style(container-row): Prettify pod badges"

- data/resources/ui/connection/creation-page.ui
- src/view/connection/creation_page.rs
> feat(connection-creation-page): Provide info about socket activation

- data/resources/ui/connection/creation-page.ui
- src/view/connection/creation_page.rs
> feat(connection-creator.page): Provide info about root

- Cargo.lock
- Cargo.toml
- README.md
- build-aux/com.github.marhkb.Pods.Devel.json
- data/resources/resources.gresource.xml
- data/resources/ui/container/details-page.ui
- data/resources/ui/container/tty-page.ui
- data/resources/ui/container/tty.ui
- meson.build
- src/view/container/details_page.rs
- src/view/container/mod.rs
- src/view/container/tty.rs
- src/view/container/tty_page.rs
- src/view/mod.rs
- src/window.rs
> feat: Implement a container terminal

- src/view/component/source_view_page.rs
- src/window.rs
> feat: Tune search action behavior

- src/view/container/log_page.rs
> fix(log-page): Always close tags at line end

- src/view/container/log_page.rs
We should keep the current format for the next log line if it hasn't
been explicitly reset by the ANSI code `0`.
> fix(container-log-page): Keep format across lines

- src/view/container/log_page.rs
Currently, we set a white foreground and a black background if we detect
the ANSI escape sequence for the default color. By doing this, we might
end up with unreadable text in light mode. Instead, we should rather
remove all specific attributes in this case.
> fix(container-log-page): Omit explicit default fg and bg color

- README.md
> chore(readme): Acknowledge GNOME CoC

- data/resources/ui/containers/group.ui
- data/resources/ui/images/panel.ui
- data/resources/ui/pods/panel.ui
To make this even look better, margins in the header suffix box have been tweaked.
> style(panels): Use circular buttons

- data/resources/ui/connection/chooser-page.ui
This fixes a regression introduced in df29d10394e9a0.
> style(connection-chooser-page): Use single-line description

- data/resources/icons/scalable/actions/pip-out-symbolic.svg
- data/resources/resources.gresource.xml
- data/resources/ui/container/tty-page.ui
- src/view/component/back_navigation_controls.rs
- src/view/container/tty_page.rs
In this way we can have a terminal while still using the application for
other things.
Fixes #646
> Make terminals detachable

- Cargo.lock
- Cargo.toml
- data/resources/resources.gresource.xml
- data/resources/ui/repo-tag/push-page.ui
- data/resources/ui/repo-tag/row.ui
- src/main.rs
- src/model/action.rs
- src/model/action_list.rs
- src/model/repo_tag.rs
- src/view/action/page.rs
- src/view/action/row.rs
- src/view/mod.rs
- src/view/repo_tag/mod.rs
- src/view/repo_tag/push_page.rs
- src/view/repo_tag/row.rs
- src/window.rs
> Enable pushing of images

- src/view/connection_creation_page.ui
- src/view/connection_row.ui
- src/view/container_details_page.ui
- src/view/container_log_page.ui
- src/view/container_properties_group.rs
- src/view/container_properties_group.ui
- src/view/containers_panel.ui
- src/view/image_details_page.rs
- src/view/image_details_page.ui
- src/view/image_history_page.rs
- src/view/image_history_page.ui
- src/view/image_search_widget.ui
- src/view/images_panel.ui
- src/view/pod_details_page.rs
- src/view/pod_details_page.ui
- src/view/pods_panel.ui
- src/view/scalable_text_view_page.rs
- src/view/scalable_text_view_page.ui
- src/view/statusbar.ui
- src/widget/efficient_spinner.rs
- src/widget/efficient_spinner.ui
- src/widget/mod.rs
- src/window.rs
> perf: Use a custom, more efficient spinner

- data/com.github.marhkb.Pods.metainfo.xml.in.in
- src/view/container_creation_page.rs
- src/view/container_creation_page.ui
> feat(container-creation-page): Add `privileged` option

- data/com.github.marhkb.Pods.metainfo.xml.in.in
- src/view/container_creation_page.rs
- src/view/container_creation_page.ui
- src/view/pod_creation_page.rs
- src/view/pod_creation_page.ui
> feat(pod-creation-page): Offer port mapping config 

- src/model/process_list.rs
Deserialization errors occur quite often. In that case, we don't want to
abort the stream.
> fix(process-list): Always continue top stream

- src/view/image_search_response_row.rs
> fix(image-search-response-row): Use correct property

- src/model/action.rs
> feat(action): Use `BufWriter` for downloading container files

- po/de.po
I tried to improve and complete the German translation.
I hope you are happy with the result,
> chore(l10n): Update German translation

- .github/workflows/ci.yml
For now, this should fix
https://github.com/flatpak/flatpak-github-actions/issues/214.
> ci: Temporarily fix failing builds

- src/model/action.rs
- src/view/action_row.rs
- change volume action type to volume
- add volume icon to action row
closes #878
> fix:[#878] volume action type
