marhkb/pods

src/application.rs, src/window.rs
We don't need to initialize the classes so early. It is enough if we do
this in the window. This also prevents the classes from being initial-
ized unnecessarily when the application should only output the version
on the command line.
=> Move class initialization from application to window

data/resources/ui/containers-panel.ui, data/resources/ui/images-panel.ui
Replacing the property `valign=start` with `vexpand=True` on the
`AdwPreferencesPages` should do the trick.
fixes #80
=> Prevent list boxes from being cut off

src/model/image_list.rs
Complete the progress bar, even if an error is encountered inspecting an image. See image for current behaviour.
I can't build and test locally because linking against libadwaita fails for some reason
```
= note: /usr/bin/ld: /home/jakob/projects/symphony/_build/src/release/deps/liblibadwaita-34cf6e2659e056e2.rlib(libadwaita-34cf6e2659e056e2.libadwaita.da37e230-cgu.8.rcgu.o): in function `libadwaita::auto::toast_overlay::ToastOverlay::add_toast':
libadwaita.da37e230-cgu.8:(.text._ZN10libadwaita4auto13toast_overlay12ToastOverlay9add_toast17h5f6dc60112fffc38E+0x16): undefined reference to `adw_toast_overlay_add_toast'
/usr/bin/ld: /home/jakob/projects/symphony/_build/src/release/deps/liblibadwaita-34cf6e2659e056e2.rlib(libadwaita-34cf6e2659e056e2.libadwaita.da37e230-cgu.8.rcgu.o): in …
```
=> image-list: fix progress bar behaviour on error

Cargo.lock, Cargo.toml, data/resources/ui/container-row.ui, src/view/container_row.rs
Instead of defining the complete menu for each container state in the ui
file, the menu can also be generated in the code. In this way entire
sections can be reused.
=> container-row: Don't duplicate menu items in code

.github/workflows/ci.yml
Else, the cache will very likley not be rebuilt properly.
=> ci/cd: Rather use hash of `Cargo.lock` as cache key

src/model/container_list.rs, src/model/simple_container_list.rs, src/view/container/container_row.rs, src/view/container/containers_panel.rs, src/view/image/image_details_page.rs
We now fire a signal whenever the name of a container has changed. This
signal will be used to update the views' sorters.
=> Improve container sorting

data/resources/ui/container-logs-panel.ui, src/view/container/container_logs_panel.rs
Also hides the cursor, since the TextView is not for input.
Please let me know if that's not the right place or method to set those properties, I'm very new to rust and GTK.
=> container-logs-panel: Use a monospaced font

src/view/container/container_logs_panel.rs
The button to scroll should be invisible If there is nothing to scroll
initially.
=> container-logs-panel: Hide scroll down button at first

data/resources/ui/image-pull-page.ui, data/resources/ui/image-search-widget.ui, data/resources/ui/image-selection-page.ui, src/view/image/image_search_widget.rs, src/view/image/image_selection_page.rs
It may be that registries are empty. In this case just hide the combo
box row.
Fixes #173
=> image-search-widget: Check for search registries

Cargo.lock, src/model/container.rs, src/model/image.rs, src/utils.rs, src/view/container/container_logs_panel.rs, src/view/image/image_pulling_page.rs, src/window.rs
In this turn changes were incorparated that to handle the API breakage
of `podman-rs` that now all API structs no longer have a `'podman`
lifetime.
=> cargo: Update dependencies

src/main.rs
This warning originates in the gettext macro. So there's nothing we can
do to prevent it.
=> clippy: Allow `format_push_string`

src/application.rs
Otherwise, the headerbar text is hardly readable when starting the
application the for the first time.
=> Fix(style): Set initial bg and fg color

Cargo.lock
The new version has a hot fix for deserializing `PortSet`, which is
needed to inspect an image.
=> fix(podman-api-rs): Update it to latest version

src/view/container/container_log_page.rs
After reloading log lines, the text iterators of the search context
become invalid. In this case, the iterators should not be used to
calculate the occurrence position.
=> fix(log-search): Avoid using invalid text iters

.github/workflows/ci.yml
Lately it fails. Probably because it exceeds the memory limit.
=> ci: Disable aarch64 build

data/resources/ui/circular-progress-bar.ui, data/resources/ui/container-row.ui, src/view/circular_progress_bar.rs
This commit removes the percentage label. In this way, it can be made
smaller. Besides, it now has a background color.
=> style(circular-progress-bar): Give it a new style

Cargo.lock, src/view/container/container_creation_page.rs
The new models in `posman-api-rs` have made most of the fields in
`LinuxResources` mandatory. This leads to errors if only individual
limits are to be set selectively. Podman then tries to set the other
limits as well. This in turn can lead to errors when starting
containers.
All fields are therefore made optional again.
Furthermore, the megabytes are now correctly converted to bytes.
=> fix(container-creation-page): Make memory limit work again

data/resources/style.css, src/model/container.rs, src/view/container/mod.rs
These were removed at some point by accident.
=> fix(container): Re-add `Stopped` and `Stopping` states

src/model/pod_list.rs
Otherwise, the number of running pods won't update in the UI.
=> fix(pod-list): Notify `running` if status has changed

.github/ISSUE_TEMPLATE/blank_issue.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
This PR adds GitHub Issue Templates that allow easier creation of issues by category. There are three options:
* Blank issue
* Bug report
* Feature request
They have some basic boilerplate and set an appropriate label when the issue is created making it easier to sort through the issues without manually going through them.
=> doc: Add issue templates

data/resources/ui/pod/creation-page.ui, src/view/pod/creation_page.rs
This PR adds options to configure the infra container when creating a pod. It's still very much a work in progress and needs cleaning up but I'm just sending it to get some feedback on the general design.
=> feat: Add infra tab to pod creation page

src/model/client.rs
It can happen that e.g. during the deletion of an image an automatic
refresh takes place. In this case there is always an internal server
error, which is displayed as a toast.
There is nothing we can do to prevent this except suppress the toast.
=> fix(client): Don't show error toast during automatic refresh

data/resources/ui/component/inspection-page.ui, data/resources/ui/container/details-page.ui, data/resources/ui/image/details-page.ui, data/resources/ui/pod/details-page.ui, src/view/component/inspection_page.rs, src/view/component/mod.rs, src/view/container/details_page.rs, src/view/image/details_page.rs, src/view/mod.rs, src/view/pod/details_page.rs
Previously, the inspection data was loaded on the corresponding detail page after pressing the button and then passed to the inspection page. But this could lead to short delays.
Therefore, in this commit, the loading of the inspection data is moved to the inspection page. This way it is possible to switch to it immediately. Until the data is loaded, a spinner is displayed.
=> feat(inspection-page): Load inspection data during construction

data/resources/ui/component/back-navigation-controls.ui
This PR updates the icon used by `back-navigation-controls` to `user-home-symbolic` as the previous icon was confusing.
New view:
Closes: #369
=> fix(back-navigation-controls): Update the icon

src/view/container/log_page.rs
This fixes two issues. The first is that timestamps where truncated. The
second issue follows from the first, because no previous log lines could
be dynamically reloaded due to the wrong timestamps.
=> fix(log-page): Parse line from the beginning

data/resources/ui/pod/creation-page.ui
This PR makes the hosts switch enabled by default. This is preferred behavior as having the switch disabled adds the `no_manage_hosts` flag that completely disables `/etc/hosts` management and it might prevent basic network communication between containers in the pod and we want defaults to just work.
=> fix(pod-creation-page): Make the hosts switch enabled by default

data/resources/ui/container/creation-page.ui, src/view/container/creation_page.rs
This commit makes the pod combo row more straight forward: First, It can
now be disabled by an entry in the list view popup making the expander
row obsolete. Secondly, pods are now ordered by their names making it
easier to find a pod.
=> style(container-creation-page): Simplify pod combo row

data/resources/ui/component/circular-progress-bar.ui, src/view/component/circular_progress_bar.rs
This commit removes the drawing area and draws the widget in the proper way by using a `GtkSnapshot`. In this turn, the style of the widget was slightly modified.
=> refactor(circular-progress-bar): Use snaphot for drawing

src/model/image.rs, src/model/image_list.rs, src/view/images/panel.rs, src/view/search_panel.rs
Images need updates. i.e. when the latest image is pulled the old image will become an intermediate. In addition, the properties of `Image` have been stripped down to only those that are actually used.
=> fix(image): Apply updates

data/resources/ui/container/rename-dialog.ui, src/view/container/rename_dialog.rs
=> style(container-rename-dialog): Use `AdwMessageDialog` as base

Cargo.lock, Cargo.toml, src/utils.rs, src/view/action/row.rs, src/view/container/commit_page.rs
We already use tokio for podman-api-rs. So there is no need to add async-std as an additional dependency.
=> refactor(ashpd): Replace `async-std` with `tokio`

src/window.rs
This prevents hitting the `Enter` key on a row in the search overview.
=> refactor(windows): Don't set search key capture widget

data/com.github.marhkb.Pods.metainfo.xml.in.in
A dash won't allow us to set a 1.1.0 release.
=> chore(app-data): Use tilde as beta separator

src/view/containers/panel.rs, src/view/images/panel.rs, src/view/pods/panel.rs, src/window.rs
This was a regression causing `Ctrl+N` to be without effect.
=> fix(window): Use correct actions to create entities

src/model/repo_tag_list.rs, src/view/search_panel.rs
fix(SearchPanel): Use to_lowercase for id and repo tag search
We used to use `to_uppercase` for this. But this will not match ids in
most cases. In addition, we don't need to convert repo tags to uppercase
because they are always lowercase.
=> fix(SearchPanel): Use to_lowercase for id and repo tag search

data/resources/ui/image/row.ui
The content of the image row wasn't vertically aligned in a way that it
complies to container and pod rows. This regression was probably
introduced in libadwaita 1.3.
=> style(image-row): Center content

data/resources/ui/image/row.ui
We should match the positions of the pod and container rows.
=> style(image-row): Fine-tune label positions

src/view/container_terminal.rs, src/view/container_terminal.ui
Changing this property to the value `ascii-delete` should fix a bug
where pressing backspace would produce `^H` in some cases.
Fixes #705
=> fix(container-terminal): Change `backspace-binding`

data/com.github.marhkb.Pods.metainfo.xml.in.in, src/view/container_terminal.rs, src/view/container_terminal_page.rs
I remember this used to work, but it must have regressed somehow.
=> fix(container-terminal): Close processes on exit

data/com.github.marhkb.Pods.metainfo.xml.in.in, src/utils.rs
Otherwise, streams run forever when we change the connection.
=> fix(utils): Stop stream on glib::ControlFlow::Break

src/view/action_page.rs
on the update_state function, update the view_artifact_button label to specify what is being viewed.
=> feat: update view label to specify what is being viewed

src/view/action_page.rs
this fixes the issue i created by accidentally making the label change default to an unreachable state :)
=> fix: prevent unreachable state caused by unmatched label
